# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

#   db:
#     build:
#       context: .
#       dockerfile: Dockerfile.mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: nodejs_dog_community_db
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 
